=== liuzhigang1996/demo/cib/src/com/neturbo/resources/neturbo-config_1_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ENTITY % BeanName "CDATA">
<!ENTITY % Boolean "(true|false|yes|no)">
<!ENTITY % ClassName "CDATA">
<!ENTITY % Integer "CDATA">
<!ENTITY % Location "#PCDATA">
<!ENTITY % PropName "CDATA">
<!ENTITY % RequestPath "CDATA">
<!ENTITY % RequestScope "(request|session)">
<!ENTITY % FieldFormat "(date|time|amount|double|numeric|phoneno|email)">
<!ENTITY % PoolType "(none|neturbo|container)">
<!ELEMENT neturbo-config (neturbo-datasources?, neturbo-forms?, global-forwards?, neturbo-actions?)>
<!ATTLIST neturbo-config
	id ID #IMPLIED
>
<!ELEMENT neturbo-datasources (datasource*)>
<!ATTLIST neturbo-datasources
	id ID #IMPLIED
>
<!ELEMENT datasource (set-property*)>
<!ATTLIST datasource
	id ID #IMPLIED
	key %BeanName; #IMPLIED
	poolType %PoolType; #IMPLIED
	type %ClassName; #IMPLIED
	autoCommit %Boolean; #IMPLIED
	description CDATA #IMPLIED
	driverClass %ClassName; #IMPLIED
	initialContext CDATA #IMPLIED
	loginTimeout %Integer; #IMPLIED
	maxCount %Integer; #IMPLIED
	minCount %Integer; #IMPLIED
	password CDATA #IMPLIED
	readOnly %Boolean; #IMPLIED
	url CDATA #IMPLIED
	user CDATA #IMPLIED
	defaultDataSource %Boolean; #IMPLIED
>
<!ELEMENT neturbo-forms (form*)>
<!ATTLIST neturbo-forms
	id ID #IMPLIED
	type %ClassName; "com.neturbo.base.action.ActionFormBean"
>
<!ELEMENT form (icon?, display-name?, description?, set-property*)>
<!ATTLIST form
	id ID #IMPLIED
	name %BeanName; #REQUIRED
	bean %ClassName; #REQUIRED
	defaultForm %Boolean; #IMPLIED
>
<!ELEMENT global-forwards (forward*)>
<!ATTLIST global-forwards
	id ID #IMPLIED
	type %ClassName; "com.neturbo.base.action.ActionForward"
>
<!ELEMENT forward (icon?, display-name?, description?, set-property*)>
<!ATTLIST forward
	id ID #IMPLIED
	className %ClassName; #IMPLIED
	name CDATA #REQUIRED
	input %RequestPath; #IMPLIED
	permission %PropName; #IMPLIED
	path %RequestPath; #REQUIRED
	redirect %Boolean; #IMPLIED
>
<!ELEMENT check-fields (field*)>
<!ELEMENT field EMPTY>
<!ATTLIST field
	name %PropName; #REQUIRED
	label %PropName; #REQUIRED
	fixlen %Integer; #IMPLIED
	maxlen %Integer; #IMPLIED
	minlen %Integer; #IMPLIED
	format %FieldFormat; #IMPLIED
	required %Boolean; #IMPLIED
>
<!ELEMENT neturbo-actions (action*)>
<!ATTLIST neturbo-actions
	id ID #IMPLIED
	type %ClassName; "com.neturbo.base.action.ActionMapping"
>
<!ELEMENT action (icon?, display-name?, description?,set-property*, forward*, check-fields?)>
<!ATTLIST action
	id ID #IMPLIED
	fid CDATA #IMPLIED
	name %RequestPath; #REQUIRED
	forward %RequestPath; #IMPLIED
	include %RequestPath; #IMPLIED
	input %RequestPath; #IMPLIED
	form %BeanName; #IMPLIED
	scope %RequestScope; #IMPLIED
	bean %ClassName; #IMPLIED
	defaultAction %Boolean; #IMPLIED
	permission %PropName; #IMPLIED
	syslog %Boolean; #IMPLIED
	clearTxnSession %PropName; #IMPLIED
	txnSession %PropName; #IMPLIED
>
<!ELEMENT set-property EMPTY>
<!ATTLIST set-property
	id ID #IMPLIED
	property %PropName; #REQUIRED
	value CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
	id ID #IMPLIED
>
<!ELEMENT display-name (#PCDATA)>
<!ATTLIST display-name
	id ID #IMPLIED
>
<!ELEMENT icon (small-icon?, large-icon?)>
<!ATTLIST icon
	id ID #IMPLIED
>
<!ELEMENT large-icon (%Location;)>
<!ATTLIST large-icon
	id ID #IMPLIED
>
<!ELEMENT small-icon (%Location;)>
<!ATTLIST small-icon
	id ID #IMPLIED
>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/navigation-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE neturbo-config PUBLIC "-//NETURBO org.// DTD NETURBO Configuration 2.0//EN" "http://www.neturbo.org.cn/resources/neturbo-config_1_0.dtd">
<neturbo-config>
  <neturbo-forms>
    <form name="ActionFormA" bean="com.neturbo.set.core.ActionFormA" defaultForm="yes"/>
  </neturbo-forms>
  <global-forwards>
    <forward name="LoginPath" path="/common/login.jsp"/>
    <forward name="ErrorReporter" path="/common/error.jsp"/>
  </global-forwards>
  <neturbo-actions>
    <action name="login" bean="app.cib.core.CorpLoginAction" input="/common/login.jsp" syslog="yes">
      <forward name="load" path="/common/login.jsp"/>
      <forward name="forceLoginLoad" path="/common/forceLogin.jsp"/>
      <forward name="forceLogin" input="/common/forceLogin.jsp" path="/common/main.jsp"/>
      <forward name="login" path="/common/main.jsp"/>
      <forward name="changePinLogin" input="/common/change_pin_res.jsp" path="/common/main.jsp"/>
      <forward name="logout" path="/common/login.jsp"/>
      <forward name="firstLogin" path="/common/change_pin.jsp"/>
      <forward name="changePin" input="/common/change_pin.jsp" path="/common/change_pin_res.jsp"/>
      <forward name="close" input="/common/close.jsp" path="/common/close.jsp"/>
    </action>
    <action name="bankLogin" bean="app.cib.core.BankLoginAction" input="/common/bank/login.jsp" syslog="yes">
      <forward name="load" path="/common/bank/login.jsp"/>
      <forward name="forceLoginLoad" path="/common/bank/forceLogin.jsp"/>
      <forward name="forceLogin" input="/common/bank/forceLogin.jsp" path="/common/bank/main.jsp"/>
      <forward name="login" path="/common/bank/main.jsp"/>
      <forward name="logout" path="/common/bank/login.jsp"/>
      <forward name="firstLogin" path="/common/bank/change_pin.jsp"/>
      <forward name="changePin" input="/common/bank/change_pin.jsp" path="/common/bank/change_pin_res.jsp"/>
      <forward name="close" input="/common/close.jsp" path="/common/close.jsp"/>
    </action>
    <action name="welcome" bean="app.cib.action.sys.WelcomeAction">
      <forward name="load" path="/common/welcome.jsp"/>
      <forward name="changePage" path="/common/main.jsp"/><!-- add by linrui for changelang in-page20190805 -->
    </action>
    <action name="bankWelcome" bean="app.cib.action.bnk.WelcomeAction">
      <forward name="load" path="/common/bank/welcome_bank.jsp"/>
    </action>
    <action name="PageProcess1" bean="app.cib.util.PageProcessor">
      <forward name="default" path="/WEB-INF/pages/error.jsp" />
    </action>
    <action name="corporation" bean="app.cib.action.bnk.CorporationAction" permission="sys.user" input="/WEB-INF/pages/bank/corp_mng/corporation_list.jsp">
      <forward name="list" path="/WEB-INF/pages/bank/corp_mng/corporation_list.jsp"/>
      <forward name="prefEntry" input="/WEB-INF/pages/bank/corp_mng/corporation_pref_entry.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_pref_entry.jsp"/>
      <forward name="view" path="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp"/>
      <forward name="addLoad" path="/WEB-INF/pages/bank/corp_mng/register_corporation.jsp"/>
      <forward name="add" input="/WEB-INF/pages/bank/corp_mng/register_corporation.jsp" path="/WEB-INF/pages/bank/corp_mng/register_corporation_confirm.jsp"/>
      <forward name="addCancel" input="/WEB-INF/pages/bank/corp_mng/register_corporation.jsp" path="/WEB-INF/pages/bank/corp_mng/register_corporation.jsp"/>
      <forward name="addConfirm" input="/WEB-INF/pages/bank/corp_mng/register_corporation_confirm.jsp" path="/WEB-INF/pages/bank/corp_mng/register_corporation_ack.jsp"/>
      <forward name="updateLoad" input="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_update.jsp"/>
      <forward name="update" input="/WEB-INF/pages/bank/corp_mng/corporation_update.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_update_confirm.jsp"/>
      <forward name="updateCancel" input="/WEB-INF/pages/bank/corp_mng/corporation_update.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_update.jsp"/>
      <forward name="updateConfirm" input="/WEB-INF/pages/bank/corp_mng/corporation_update_confirm.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_update_ack.jsp"/>
      <forward name="delete" input="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_delete_confirm.jsp"/>
      <forward name="deleteCancel" input="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp"/>
      <forward name="deleteConfirm" input="/WEB-INF/pages/bank/corp_mng/corporation_delete_confirm.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_delete_ack.jsp"/>
      <forward name="block" input="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_block_confirm.jsp"/>
      <forward name="blockCancel" input="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp"/>
      <forward name="blockConfirm" input="/WEB-INF/pages/bank/corp_mng/corporation_block_confirm.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_block_ack.jsp"/>
      <forward name="unblock" input="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_unblock_confirm.jsp"/>
      <forward name="unblockCancel" input="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_view.jsp"/>
      <forward name="unblockConfirm" input="/WEB-INF/pages/bank/corp_mng/corporation_unblock_confirm.jsp" path="/WEB-INF/pages/bank/corp_mng/corporation_unblock_ack.jsp"/>
      <forward name="listCorpForTree" permission="" input="/WEB-INF/pages/bank/corp_mng/dlg_corp_tree.jsp" path="/WEB-INF/pages/bank/corp_mng/dlg_corp_tree.jsp"/>
      <forward name="checkConfig" input="/WEB-INF/pages/bank/corp_mng/config_checking_result.jsp" path="/WEB-INF/pages/bank/corp_mng/config_checking_result.jsp"/>
    </action>
    <action name="bankUser" bean="app.cib.action.bnk.BankUserAction" permission="bnk.user,srv.bank.supervisor" input="/WEB-INF/pages/bank/bank_user/bankUser_list.jsp">
      <forward name="list" path="/WEB-INF/pages/bank/bank_user/bankUser_list.jsp"/>
      <forward name="view" path="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp"/>
      <forward name="addLoad" path="/WEB-INF/pages/bank/bank_user/bankUser_add.jsp"/>
      <forward name="add" input="/WEB-INF/pages/bank/bank_user/bankUser_add.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_add_confirm.jsp"/>
      <forward name="addCancel" input="/WEB-INF/pages/bank/bank_user/bankUser_add.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_add.jsp"/>
      <forward name="addConfirm" input="/WEB-INF/pages/bank/bank_user/bankUser_add_confirm.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_add_ack.jsp"/>
      <forward name="updateLoad" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_update.jsp"/>
      <forward name="update" input="/WEB-INF/pages/bank/bank_user/bankUser_update.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_update_confirm.jsp"/>
      <forward name="updateCancel" input="/WEB-INF/pages/bank/bank_user/bankUser_update.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_update.jsp"/>
      <forward name="updateConfirm" input="/WEB-INF/pages/bank/bank_user/bankUser_update_confirm.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_update_ack.jsp"/>
      <forward name="delete" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_delete_confirm.jsp"/>
      <forward name="deleteCancel" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp"/>
      <forward name="deleteConfirm" input="/WEB-INF/pages/bank/bank_user/bankUser_delete_confirm.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_delete_ack.jsp"/>
      <forward name="block" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_block_confirm.jsp"/>
      <forward name="blockCancel" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp"/>
      <forward name="blockConfirm" input="/WEB-INF/pages/bank/bank_user/bankUser_block_confirm.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_block_ack.jsp"/>
      <forward name="unblock" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_unblock_confirm.jsp"/>
      <forward name="unblockCancel" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp"/>
      <forward name="unblockConfirm" input="/WEB-INF/pages/bank/bank_user/bankUser_unblock_confirm.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_unblock_ack.jsp"/>
      <forward name="setPasswordLoad" path="/WEB-INF/pages/bank/bank_user/setPassword.jsp"/>
      <forward name="setPassword" input="/WEB-INF/pages/bank/bank_user/setPassword.jsp" path="/WEB-INF/pages/bank/bank_user/setPassword_ack.jsp"/>
      <forward name="resetPassword" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/resetPassword_confirm.jsp"/>
      <forward name="resetPasswordCancel" input="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_view.jsp"/>
      <forward name="resetPasswordConfirm" input="/WEB-INF/pages/bank/bank_user/resetPassword_confirm.jsp" path="/WEB-INF/pages/bank/bank_user/resetPassword_ack.jsp"/>
      <forward name="listOperationHistoryLoad" input="/WEB-INF/pages/bank/bank_user/bankUser_history.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_history.jsp"/>
      <forward name="listOperationHistory" input="/WEB-INF/pages/bank/bank_user/bankUser_history_list.jsp" path="/WEB-INF/pages/bank/bank_user/bankUser_history_list.jsp"/>
