=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/fieldchecking.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by nabai (enlogic) -->
<!ENTITY % Boolean "(true|false|yes|no)">
<!ENTITY % Integer "CDATA">
<!ENTITY % PropName "CDATA">
<!ENTITY % FieldFormat "(string|numonly|engonly|engnum|date|time|amount|integer|phoneno|email)">
<!ELEMENT fieldchecking (group*)>
<!ELEMENT group (field*)>
<!ATTLIST group
	name %PropName; #REQUIRED
>
<!ELEMENT field (format?, depend*, reject*)>
<!ATTLIST field
	name %PropName; #REQUIRED
	label %PropName; #REQUIRED
	required %Boolean; #IMPLIED
>
<!ELEMENT format (#PCDATA)>
<!ATTLIST format
	type %PropName; #REQUIRED
	fixlen %Integer; #IMPLIED
	maxlen %Integer; #IMPLIED
	minlen %Integer; #IMPLIED
	prefix %Integer; #IMPLIED
	suffix %Integer; #IMPLIED
>
<!ELEMENT depend (#PCDATA)>
<!ATTLIST depend
	prompt %PropName; #REQUIRED
>
<!ELEMENT reject (#PCDATA)>
<!ATTLIST reject
	prompt %PropName; #REQUIRED
>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/set_password.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="setPassword">
	<!--  update by liang_ly for CR204 2015-4-10 -->
		<field name="oldPassword" label="Old_Password" required="yes">
			<format type="String" />
		</field>
	
	    <field name="newPassword" label="New_Password" required="yes">
			<format type="String" />
			<!--  update by liang_ly for CR204 2015-4-10	
			<reject prompt="Password_Info1">[newPassword]!='' &amp;&amp; [newPassword]==[oldPassword]</reject>
			-->
			<reject prompt="Password_Range">([newPassword].length &lt; pin_min) || ([newPassword].length &gt; pin_max)</reject>
			<reject prompt="Password_Upper_Lower">(parseInt([checkUpperNum]) &lt; pin_upper) || (parseInt([checkLowerNum]) &lt; pin_lower)</reject>
			
			<!-- add by long_zg 2015-06-24 for CR210 New policy to BOB/BOL password -->
			<reject prompt="Char_Num_Only">checkCharNum([newPassword])</reject>
			<reject prompt="Password_UserId_Same">([newPassword].toLowerCase()  == [userId].toLowerCase())</reject>
			<reject prompt="Password_UserId_Reverse_Same">([newPassword].toLowerCase()  == ([userId].split('').reverse().join('')).toLowerCase())</reject>
			<reject prompt="Password_Include_IdNo">((''!=[idNo]) &amp;&amp; (-1 != ([newPassword].toLowerCase() .indexOf((eliminate([idNo])).toLowerCase()))))</reject>
			
		</field>
		<field name="confirmPassword" label="Confirm_Password" required="yes">
			<format type="String" />
			<depend prompt="Password_Info">[confirmPassword]!='' &amp;&amp; [newPassword]==[confirmPassword]</depend>
		</field>
	</group>
	<group name="setSecurityCode">
		<field name="oldSecurityCode" label="Old_S_Code" required="yes">
			<format type="String" />
		</field>
	    <field name="newSecurityCode" label="New_S_Code" required="yes">
			<format type="String" />
			<reject prompt="Security_Code_Info1">[newSecurityCode]!='' &amp;&amp; [newSecurityCode]==[oldSecurityCode]</reject>
			<reject prompt="SecurityCode_Range">([newSecurityCode].length &lt; pin2_min) || ([newSecurityCode].length &gt; pin2_max)</reject>
			<reject prompt="SecurityCode_Upper_Lower">(parseInt([checkUpperNum]) &lt; pin2_upper) || (parseInt([checkLowerNum]) &lt; pin2_lower)</reject>
			
			<!-- add by long_zg 2015-06-24 for CR210 New policy to BOB/BOL password -->
			<reject prompt="Char_Num_Only">checkCharNum([newSecurityCode])</reject>
			<reject prompt="Password_UserId_Same">([newSecurityCode].toLowerCase()  == [userId].toLowerCase())</reject>
			<reject prompt="Password_UserId_Reverse_Same">([newSecurityCode].toLowerCase()  == ([userId].split('').reverse().join('')).toLowerCase())</reject>
			<reject prompt="Password_Include_IdNo">((''!=[idNo]) &amp;&amp; (-1 != ([newSecurityCode].toLowerCase() .indexOf((eliminate([idNo])).toLowerCase()))))</reject>
			
		</field>
		<field name="confirmSecurityCode" label="New_S_Code_Confirm" required="yes">
			<format type="String" />
			<depend prompt="Security_Code_Info">[confirmSecurityCode]!='' &amp;&amp; [newSecurityCode]==[confirmSecurityCode]</depend>
		</field>
	</group>

	<group name="bank_setPassword">
		<field name="oldPassword" label="Old_Password" required="yes">
			<format type="String" minlen="6" />
		</field>
	        <field name="newPassword" label="New_Password" required="yes">
			<format type="String" minlen="6" />
			<reject prompt="Password_Info1">[newPassword]!='' &amp;&amp; [newPassword]==[oldPassword]</reject>
		</field>
		<field name="confirmPassword" label="Confirm_Password" required="yes">
			<format type="String" />
			<depend prompt="Password_Info">[confirmPassword]!='' &amp;&amp; [newPassword]==[confirmPassword]</depend>
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/corp_user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="corpUser">
		<!-- modified by lzg 20190704 -->
		<!--<field name="userId" label="User_Id" required="yes">
			<format type="string" />
		</field>
		-->
		<field name="userId" label="User_Id">
			<format type="engmust" />
			<reject prompt="userId_Length_Reject">[userId].length &lt; 8 || [userId].length &gt; 16</reject>
		</field>
		<!-- modified by lzg end -->
		<!-- modified by lzg 20190618 -->
		<field name="userName" label="User_Name" required="yes">
			<format type="string"/>
		</field>
		
		<!--<field name="title" label="Title" required="yes">
			<format type="string"/>
		</field>
		--><!-- modified by lzg end -->
		<!-- add by lzg 20190618 -->
		<field name="fullName" label="Full_Name" required="yes">
			<format type="string"/>
		</field>
		<field name="idNo" label="ID_NO" required="yes">
			<format type="string"/>
		</field>
		<!-- add by lzg end -->
		<field name="email" label="Email" required="yes">
			<format type="email"/>
		</field>
		<field name="idIssueDate" label="ID_Issue_date">
		     <format type="date" />
		</field>
		<!--<field name="certInfo1" label="Cert_Info1">
			<format type="string"/>
			<reject prompt="Approver_CerInfo1">[roleId] == "2" &amp; [authenticationMode] == "C" &amp; [certInfo1]==""</reject>
		</field>
		-->
		<field name="authLevel" label="Authoriztion_Level"> 
			<format type="string"/>
			<reject prompt="AuthLevel_Required">[roleId]=="2" &amp; [authLevel]==""</reject>
		</field>
		<!-- Modify by long_zg 2019-05-22 UAT6-245 COB：四種轉賬的名稱需要更改 begin -->
		<!--
		<field name="limit1" label="Own_Accounts">
			<format type="amount"/>
			<reject prompt="Own_Accounts_Required">[roleId]=="1" &amp; [limit1]==""</reject>
		</field>
		<field name="limit2" label="Accounts_BANK">
			<format type="amount"/>
			<reject prompt="Accounts_BANK_Required">[roleId]=="1" &amp; [limit2]==""</reject>
		</field>
		<field name="limit3" label="Accounts_Macau">
			<format type="amount"/>
			<reject prompt="Accounts_Macau_Required">[roleId]=="1" &amp; [limit3]==""</reject>
		</field>
		<field name="limit4" label="Accounts_Overseas">
			<format type="amount"/>
			<reject prompt="Accounts_Overseas_Required">[roleId]=="1" &amp; [limit4]==""</reject>
		</field>
		-->
		<field name="limit1" label="TO_MY_ACCOUNT">
			<format type="amount"/>
			<reject prompt="TO_MY_ACCOUNT_Required">[roleId]=="1" &amp; [limit1]==""</reject>
		</field>
		<field name="limit2" label="TO_MDB_BANK_ACCOUNT">
			<format type="amount"/>
			<reject prompt="TO_MDB_BANK_ACCOUNT_Required">[roleId]=="1" &amp; [limit2]==""</reject>
		</field>
		<field name="limit3" label="TO_LOCAL_BANK_ACCOUNT">
			<format type="amount"/>
			<reject prompt="TO_LOCAL_BANK_ACCOUNT_Required">[roleId]=="1" &amp; [limit3]==""</reject>
		</field>
		<field name="limit4" label="TO_OVERSEAS_BANK_ACCOUNT">
			<format type="amount"/>
			<reject prompt="TO_OVERSEAS_BANK_ACCOUNT_Required">[roleId]=="1" &amp; [limit4]==""</reject>
		</field>
		<!-- Modify by long_zg 2019-05-22 UAT6-245 COB：四種轉賬的名稱需要更改 end -->
		
		<!--<field name="limit5" label="Corp_Fund_Alloc">
			<format type="amount"/>
			<reject prompt="Corp_Fund_Alloc_Required">[roleId]=="1" &amp; [limit5]==""</reject>
		</field>
		<field name="limit6" label="Bill_Payment">
			<format type="amount"/>
			<reject prompt="Bill_Payment_Required">[roleId]=="1" &amp; [limit6]==""</reject>
		</field>
		--><field name="limit7" label="Time_Deposit">
			<format type="amount"/>
			<reject prompt="Time_Deposit_Required">[roleId]=="1" &amp; [limit7]==""</reject>
		</field>
		<!--<field name="limit8" label="Payroll">
			<format type="amount"/>
			<reject prompt="Payroll_Required">[roleId]=="1" &amp; [limit8]==""</reject>
		</field>
		<field name="limit9" label="Bank_Draft">
			<format type="amount"/>
			<reject prompt="Bank_Draft_Required">[roleId]=="1" &amp; [limit9]==""</reject>
		</field>
		<field name="limit10" label="Cashier_Order">
			<format type="amount"/>
			<reject prompt="Cashier_Order_Required">[roleId]=="1" &amp; [limit10]==""</reject>
		</field>
		--><!-- modified by lzg 20190624 -->
		<!-- modify by long_zg 2014-04-03 for CR204 Apply OTP to BOB begin -->
		<!--<field name="mobile" label="Mobile_Telephone">
			<format type="numonly"/>
			<reject prompt="Mobile_Telephone_Required">([roleId]=="2" || ([otpLogin]=="Y" &amp; [authenticationMode]=="C")) &amp; [mobile]==""</reject>
		</field>
		-->
		<field name="mobile" label="Mobile_Telephone" required="yes">
			<format type="string"/>
		</field>
		<!-- modified by lzg end -->
		<!--<field name="mobile" label="Mobile_Telephone">
			<format type="numonly"/>
			<reject prompt="Mobile_Country_Code_Required">[roleId]=="2"</reject> 
			<reject prompt="Mobile_Country_Code_Invalid">!(/^\d{0,3}$/).test([mobileCountryCode])</reject>
		</field>
		<field name="mobile" label="Mobile_Telephone">
			<format type="numonly"/>
		 	<reject prompt="Mobile_Area_Code_Required">[roleId]=="2"</reject> 
			<reject prompt="Mobile_Area_Code_Invalid">!(/^\d{0,3}$/).test([mobileAreaCode])</reject>
		</field>
		--><!-- modify by long_zg 2014-04-03 for CR204 Apply OTP to BOB end -->

	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/cheque_book_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="add">
		<!--<field name="accountNo" label="Current_Account" required="true" />-->
		<field name="accountNo" label="Current_Account" required="no">
			<format type="string" />
			<reject prompt="Required">document.getElementById("accountNo").selectedIndex == 0</reject>
		</field>
		<field name="payCurrency" label="From_ccy" required="no">
			<format type="string" />
			<reject prompt="Required">document.getElementById("payCurrency").selectedIndex == 0</reject>
			<!-- Add by long_zg 2019-05-31 UAT6-464 COB：COB：申請支票報錯，交易記錄也不見了 begin -->
			<reject prompt="CurrencyNoAllow">document.getElementById("payCurrency").value != 'HKD' &amp;&amp; document.getElementById("payCurrency").value != 'MOP' </reject>
			<!-- Add by long_zg 2019-05-31 UAT6-464 COB：COB：申請支票報錯，交易記錄也不見了 end -->
		</field>
		<!-- mod by linrui 20190514 -->
		
		<field name="noOfBook" label="No_Of_Books" required="true">
			<format maxlen="2" type="numonly" />
			<reject prompt="No_Of_Books_Large">
			[noOfBook] &gt; 10
			</reject>
			<reject prompt="No_Of_Books_Invaild">
			[noOfBook] == 0
			</reject>
		</field>
		<field name="pickupBranchCode" label="Pickup_Branch" required="true" />
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/schedule_transfer_macau.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="schedule_macau">
	   <field name="scheduleName" label="Schedule_Name" required="yes">
			<format type="String" />
		</field>
		<field name="dayType" label="Frequence" required="yes">
			<reject prompt="Weekly_Justify">
				[dayType]=="2" &amp;&amp; [frequenceWeekDays]==null
			</reject>
			<reject prompt="Monthly_Justify">
				[dayType]=="3" &amp;&amp; [month_type]==null
			</reject>
			<reject prompt="monthly_designed_day_format_error">
				[dayType]=="3" &amp;&amp; [month_type]==0 &amp;&amp;
				([designed_day]&lt;1 || [designed_day]&gt;31)
			</reject>
			<reject prompt="Days_per_month_Justify">
				[dayType]=="4" &amp;&amp; [days_per_month]==""
			</reject>
		</field>
		<field name="fromAccount" label="Account Number" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("fromAccount").selectedIndex == 0</reject>
		</field>
		<field name="fromCurrency" label="From Currency" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("fromCurrency").selectedIndex == 0</reject>
			<reject prompt="fromCurrency_Justify_1">document.getElementById("fromCurrency").value=="CNY"</reject>
		</field>
		<field name="toCurrency" label="To Currency" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("toCurrency").selectedIndex == 0</reject>
			<!-- add by lzg 20190613 -->
			<reject prompt="toCurrency_Justify">document.getElementById("toCurrency").value != "MOP" &amp;&amp; document.getElementById("toCurrency").value != "HKD" &amp;&amp; document.getElementById("toCurrency").value != "USD" &amp;&amp; document.getElementById("toCurrency").value != "EUR"</reject>
			<!-- add by lzg end -->
		</field>
		<field name="transferAmount" label="To_Amount">
			<format type="amount" />
			<reject prompt="Amount_Justify">([transferAmount]=="" &amp;&amp; [debitAmount]=="") || ([transferAmount]== 0 &amp;&amp; [debitAmount]== 0)</reject>
			<reject prompt="Amount_Justify_1">[transferAmount]&lt;10 &amp;&amp; [debitAmount]&lt;10 </reject>
		</field>
		<field name="beneficiaryName1" label="Beneficiary_Name">
			<format type="common" />
		</field>
		<field name="beneficiaryName2" label="Beneficiary_Name">
			<format type="common" />
			<reject prompt="Please enter the Beneficiary Account Name">([beneficiaryName1]=="" &amp;&amp; [beneficiaryName2]=="")</reject>
		</field>
		<field name="beneJustify" label="Beneficiary_Name">
			<format type="string" />
			<reject prompt="Not Allow to input single word in Beneficiary Name">[beneJustify]=='Y'</reject>
		</field>
		<field name="beneficiaryBank" label="Beneficiary_Bank"
			required="yes">
			<format type="string" />
		</field>
		<field name="toAccount" label="Beneficiary Account" required="yes">
			<format type="common" />
			<reject prompt="Account_Justify">
				[fromAccount]==[toAccount]
			</reject>
		</field>
		<field name="chargeBy" label="Commission_charges_by" required="yes">
			<format type="string" />
		</field>
		<field name="messsage" label="Message_Send">
			<format type="common" />
		</field>
		<field name="messsage2" label="Message_Send">
			<format type="common" />
		</field>
		<field name="requestType" label="Transfer_Date"	required="yes">
			<format type="string" />
		</field>
		<field name="debitAmount" label="Transfer_Info1" >
			<format type="amount" />
		</field>
		<field name="chareBy" label="Charges_By" required="yes">
			<format type="string" />
		</field>
		<!--<field name="remark" label="Remark" >
			<format type="common" />
		</field>
		--><!-- add by linrui 20190531 -->
		<field name="endDate" label="Transfer_End_Date" required="yes">
			<format type="date"/>
		</field>
		
		<!-- add by lzg 20190602 -->
		<field name="purposeCode" label="Purpose" required="no">
			<reject prompt="Required">document.getElementById("purposeCode").selectedIndex == 0</reject>
		</field>
		<!-- add by lzg end -->
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/message_manage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="add">
		<field name="msgTitle" label="Message_Title" required="yes">
			<format type="string" />
		</field>
		<field name="fromDate" label="From_Date" required="yes">
			<format type="date" />
			<reject prompt="Date_Justify">(getDateValue([fromDate])>getDateValue([toDate]))</reject>
		</field>
		<field name="toDate" label="To_Date" required="yes">
			<format type="date" />
		</field>
		<field name="msgContent" label="Message_Content"
			required="yes">
			<format type="string" minlen="10" maxlen="200" />
		</field>
	</group>
	<group name="bank_list">
		<field name="messageId" label="Message_ID" required="yes" />
	</group>
	<group name="corp_list">
		<field name="messageId" label="muId" required="yes" />
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/cash_order.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
  <group name="cash_order_history">
	    <field name="fromAccount" label="Account_Number" required="yes">
			<format type="numonly" />
		</field>
		<field name="begin_time" label="Begin_time">
		     <format type="date" />
			<reject prompt="Date_Justify">[date_range]=="range" &amp;&amp; ((getDateValue([begin_time])>getDateValue([end_time]) &amp;&amp; [end_time] != "")|| (([begin_time]=="") &amp;&amp; ([end_time]=="")))</reject>
		</field>
		<field name="end_time" label="End_time">
		     <format type="date" />
		</field>
	</group>
	<group name="cash_order_requst">
	<field name="fromAccount" label="Account_Number" required="yes">
		<format type="numonly" />
	</field>
	<field name="toCurrency" label="Currency" required="yes">
		<format type="string" />
	</field>
	<field name="totalNumber" label="Cash_Number" required="yes">
		<format type="numonly" />
		<reject prompt="totalNumber_justify">
				([totalNumber]&lt;1 || [totalNumber]&gt;4)
			</reject>
	</field>
	<field name="toAmount" label="Total_Amount" required="yes">
		<format type="amount" />
	</field>
	<field name="chargeBy" label="Charges_From" required="yes">
		 <format type="string" />
		 <reject prompt="OtherAccount_Justify">[chargeBy]=="2" &amp;&amp; [chargeAccount]==""</reject>
	</field>	
		
	</group>
	
	<group name="cash_order_detail">
	<field name="fromAccount" label="Account_Number" required="yes">
		<format type="numonly" />
	</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/check_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="stop_check">
	<field name="chequeNumber" label="Cheque_Number" required="yes">
		<format type="numonly" />
		<reject prompt="ChequeNumber_Checking">[chequeNumber]=="0"</reject>
	</field>
	<!--<field name="currentAccount" label="Account" required="yes">
			<format type="numonly" />
	</field>
	-->
	<field name="currentAccount" label="Account" required="no">
			<format type="string" />
			<reject prompt="Required">document.getElementById("currentAccount").selectedIndex == 0</reject>
		</field>
		<field name="currentAccountCcy" label="From_ccy" required="no">
			<format type="string" />
			<reject prompt="Required">document.getElementById("currentAccountCcy").selectedIndex == 0</reject>
		</field>
		<!-- mod by linrui 20190514 -->
	
	<field name="amount" label="Amount" required="no">
		<format type="amount" />
		<reject prompt="Amount_Checking">[amount]&lt;0  <!-- || [amount]==0 --></reject>
	</field>	
	<field name="issueDate" label="Issue_date" required="no">
	   <format type="date" />
	</field>
	<field name="expiryDate" label="Expiry_date" required="no">
	  <format type="date" />
	</field>
	<field name="reason" label="Reason_for_stop" required="yes">
		<format type="string" />
	</field>
	<field name="stopReason" label="Reason_for_stop" required="no">
		<format type="string" />
		<reject prompt="Specific_Reason">document.getElementsByName("reason")[0].checked &amp;&amp; document.getElementById("stopReason").selectedIndex == 0</reject>
	</field>
	<field name="stopOtherReason" label="Reason_for_stop" required="no">
		<format type="string" />
		<reject prompt="Other_Reason">document.getElementsByName("reason")[1].checked &amp;&amp; document.getElementById("stopOtherReason").value==''</reject>
	</field>
		
	</group>
	
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/corp_mng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="pref_entry">
		<field name="corpId" label="Corp_Id" required="yes">
			<format type="string" maxlen="12"/>
		</field>
	</group>
	<group name="new_corp">
		<field name="cifNo" label="Cif_No" required="yes"><!-- update by linrui 20180211 -->
			<format type="string" maxlen="10"/>
		</field>
		<!-- modified by lzg 20190618 -->
		<field name="corpName" label="Corp_Name" required="yes">
			<format type="string"/>
		</field>
		
		<!-- modified by lzg end -->
		<field name="corpType" label="corp_type">
			<format type="string"/>
			<reject prompt="type_seleted">[corpType]=="0"</reject>
		</field>
		<field name="authenticationMode" label="AUTHENTICATION_MODE">
			<format type="string"/>
			<reject prompt="authentication_seleted">[authenticationMode]=="0"</reject>
		</field>
		<!-- modified by lzg 20190618-->
		<!--<field name="timeZone" label="Time_Zone" required="yes">
			<format type="integer"/>
		</field>
		-->
		<!-- modified by lzg end -->
		<!-- add by lzg 20190618 -->
		<field name="fullName" label="Full Name" required="yes">
			<format type="string"/>
		</field>
		<field name="commercialRegistryNo" label="Commercial Registry No." required="yes">
			<format type="string"/>
		</field>
		<field name="telephone" label="Telephone" required="yes">
			<format type="string"/>
		</field>
		
		<!-- add by lzg end -->
		<field name="email" label="Email" >
			<format type="email"/>
		</field>
		<field name="rep1Email" label="Email" >
			<format type="email"/>
		</field>
		<field name="rep2Email" label="Email" >
			<format type="email"/>
		</field>
		<field name="rep1IdIssueDate" label="ID_Issue_date">
		     <format type="date" />
		</field>
		<field name="rep2IdIssueDate" label="ID_Issue_date">
		     <format type="date" />
		</field>
	</group>
</fieldchecking>
