=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/fieldchecking.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by nabai (enlogic) -->
<!ENTITY % Boolean "(true|false|yes|no)">
<!ENTITY % Integer "CDATA">
<!ENTITY % PropName "CDATA">
<!ENTITY % FieldFormat "(string|numonly|engonly|engnum|date|time|amount|integer|phoneno|email)">
<!ELEMENT fieldchecking (group*)>
<!ELEMENT group (field*)>
<!ATTLIST group
	name %PropName; #REQUIRED
>
<!ELEMENT field (format?, depend*, reject*)>
<!ATTLIST field
	name %PropName; #REQUIRED
	label %PropName; #REQUIRED
	required %Boolean; #IMPLIED
>
<!ELEMENT format (#PCDATA)>
<!ATTLIST format
	type %PropName; #REQUIRED
	fixlen %Integer; #IMPLIED
	maxlen %Integer; #IMPLIED
	minlen %Integer; #IMPLIED
	prefix %Integer; #IMPLIED
	suffix %Integer; #IMPLIED
>
<!ELEMENT depend (#PCDATA)>
<!ATTLIST depend
	prompt %PropName; #REQUIRED
>
<!ELEMENT reject (#PCDATA)>
<!ATTLIST reject
	prompt %PropName; #REQUIRED
>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/transfer_BANK.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<!-- modified by lzg for GAPMC-EB-001-0050 -->
    <group name="transferInBANK">
		<field name="fromAccount" label="From_Account" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("fromAccount").selectedIndex == 0</reject>
		</field>
		<field name="fromCurrency" label="From_ccy" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("fromCurrency").selectedIndex == 0</reject>
		</field>
		<field name="toAccount" label="To_Account" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("toAccount").selectedIndex == 0</reject>
			<!--<reject prompt="Account_Justify">[fromAccount]==[toAccount]</reject>-->
		</field>
		<field name="toCurrency" label="To_ccy" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("toCurrency").selectedIndex == 0</reject>
		</field>
		<field name="transferAmount" label="Amount_Justify_lable" >
			<format type="amount" />
			<reject prompt="Amount_Justify">([transferAmount]=="" &amp;&amp; [debitAmount]=="") || ([transferAmount]== 0 &amp;&amp; [debitAmount]== 0)</reject>
			<reject prompt="Amount_Justify_1">[transferAmount]&lt;10 &amp;&amp; [debitAmount]&lt;10 </reject>
		</field>
		<field name="debitAmount" label="Transfer_Info1" >
			<format type="amount" />
		</field>
		<field name="toName" label="To_Name">
		    <format type="string" />
		    <reject prompt="Name_Justify">[toAccount]==0 &amp;&amp; [toName]==""</reject>
		</field>
		<!-- add by linrui for remarkTohost 120 20190911 -->
		<field name="remarkHost" label="Remark_Host">
			<format type="string" minlen="0" maxlen="120"/>
		</field>
		<!-- end by linrui for remarkTohost 120 20190911 -->
	</group>
	<!-- modified by lzg end -->
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/transfer_template_macau.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="templateInMacau">
		<field name="fromAccount" label="From_Account" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("fromAccount").selectedIndex == 0</reject>
		</field>
		<field name="fromCurrency" label="From_ccy" required="no">
			<format type="string" />
			<reject prompt="Required">document.getElementById("fromCurrency").selectedIndex == 0</reject>
			<reject prompt="fromCurrency_Justify_1">document.getElementById("fromCurrency").value=="CNY"</reject>
		</field>
		<field name="toCurrency" label="To_Currency" required="no">
			<format type="string" />
			<reject prompt="Required">document.getElementById("toCurrency").selectedIndex == 0</reject>
			<!-- add by lzg 20190613 -->
			<reject prompt="toCurrency_Justify">document.getElementById("toCurrency").selectedIndex != 0&amp;&amp;document.getElementById("toCurrency").value != "MOP" &amp;&amp; document.getElementById("toCurrency").value != "HKD" &amp;&amp; document.getElementById("toCurrency").value != "USD" &amp;&amp; document.getElementById("toCurrency").value != "EUR"</reject>
			<!-- add by lzg end -->
		</field>
		<field name="transferAmount" label="Amount_Justify_lable" >
			<format type="amount" />
			<reject prompt="Amount_Justify">([transferAmount]=="" &amp;&amp; [debitAmount]=="") || ([transferAmount]== 0 &amp;&amp; [debitAmount]== 0)</reject>
			<reject prompt="Amount_Justify_1">[transferAmount]&lt;10 &amp;&amp; [debitAmount]&lt;10 </reject>
		</field>
		<field name="beneficiaryBank" label="Beneficiary_Bank" required="yes">
			<format type="string" />
		</field>
		<field name="toAccount" label="Beneficiary_Account" required="yes">
			<format type="common" />
			<reject prompt="Account_Justify">[fromAccount]==[toAccount]</reject>
		</field>
		<field name="requestType" label="Transfer_Date" required="yes">
			<format type="string" />
		</field>
		<field name="transferDateString" label="Transfer_Date">
			<format type="date" />
			<reject prompt="Date_Justify">[requestType]=='2' &amp;&amp; [transferDateString] == ''</reject><!--mod by linrui for mul-language 20171123  -->
		</field>
		<field name="debitAmount" label="Transfer_Info1" >
			<format type="amount" />
		</field>
		<!-- <field name="chareBy" label="Charges_By" required="yes">
			<format type="string" />
		</field> -->
		<field name="beneficiaryName1" label="Beneficiary_Name">
			<format type="common" />
		</field>
		<field name="beneficiaryName2" label="Beneficiary_Name">
			<format type="common" />
			<reject prompt="Beneficiary_Justify">([beneficiaryName1]=="" &amp;&amp; [beneficiaryName2]=="")</reject>
		</field>
		<field name="beneJustify" label="Beneficiary_Name">
			<format type="string" />
			<reject prompt="Beneficiary_Name_Justify">[beneJustify]=='Y'</reject>
		</field>
		<!-- <field name="chargeBy" label="Commission_charges_by" required="yes">
			<format type="string" />
		</field> -->
		<field name="messsage" label="Message_Send">
			<format type="common" />
		</field>
		<field name="messsage2" label="Message_Send">
			<format type="common" />
		</field>
		<field name="messsage3" label="Message_Send">
			<format type="common" />
		</field>
		
		<!--<field name="remark" label="Remark" >
			<format type="common" />
		</field>
		-->
		<!-- add by linrui 20191008 -->  
		<field name="chargeAccount" label="Deduct_Charge_from_Account" required="no">
			<reject prompt="Required">document.getElementsByName('chargeBy')[0].checked != true &amp;&amp; document.getElementById("chargeAccount").selectedIndex == 0 </reject>
		</field> 
		<!-- add by linrui end -->
		<!-- add by lzg 20190602 -->
		<field name="purposeCode" label="Purpose" required="no">
			<reject prompt="Required">document.getElementById("purposeCode").selectedIndex == 0</reject>
		</field>
		<!-- add by lzg end -->
		</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/batch_transfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
    
    <group name="transferInBankStM">
	<field name="uploadFile" label="choose_file" required="yes">
	</field>	
	</group>
	<group name="transferInBankMtS">
	<field name="uploadFile" label="choose_file" required="yes">
	</field>	
	</group>
	<group name="transferInMacauStM">
	<field name="uploadFile" label="choose_file" required="yes">
	</field>	
	</group>
	<group name="transferInOverseaStM">
	<field name="uploadFile" label="choose_file" required="yes">
	</field>	
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/corp_transfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
    <group name="corpHistory">
		<field name="fromAccount" label="Account_Number" required="yes">
			<format type="numonly" />
		</field>
		<field name="fromCorporation" label="Corporation" required="yes">
			<format type="string" />
		</field>
		<field name="dateFrom" label="date_from" required="no">
			<format type="date"/>
			<reject prompt="Date_Justify">[date_range]=="range" &amp;&amp; ((getDateValue([dateFrom])>getDateValue([dateTo]) &amp;&amp; [dateTo] != "") || (([dateFrom]=="") &amp;&amp; ([dateTo]=="")))</reject>
        </field>
		<field name="dateTo" label="date_to" required="no">
			<format type="date"/>
		</field>
	</group>
	<group name="corpDelivery">
		<field name="fromAccount" label="From_Account" required="yes">
			<format type="numonly" />
		</field>
		<field name="toAccount" label="To_Account" required="yes">
			<format type="numonly" />
			<reject prompt="From Account can not be the same as to Account">[fromAccount]==[toAccount]</reject>
		</field>
		<field name="toCorporation" label="To_Corporation" required="yes">
			<format type="string" />
		</field>
		<field name="transferAmount" label="To_Amount" >
			<format type="amount" />
			<reject prompt="Amount_Justify">([transferAmount]=="" &amp;&amp; [debitAmount]=="") || ([transferAmount]== 0 &amp;&amp; [debitAmount]== 0)</reject>
			<reject prompt="Amount_Justify_1">[transferAmount]&lt;0 &amp;&amp; [debitAmount]&lt;0 </reject>
		</field>
		<field name="debitAmount" label="Transfer_Amount_Info2" >
			<format type="amount" />
		</field>		
	</group>
	<group name="corpSubsidiary">
		<field name="fromCorporation" label="From_Corporation" required="yes">
			<format type="string" />
		</field>
		<field name="fromAccount" label="From_Account" required="yes">
			<format type="numonly" />
		</field>
		<field name="toCorporation" label="To_Corporation" required="yes">
			<format type="string" />
		</field>
		<field name="toAccount" label="To_Account" required="yes">
			<format type="numonly" />
			<reject prompt="From Account can not be the same as to Account">[fromAccount]==[toAccount]</reject>
		</field>
		<field name="transferAmount" label="To_Amount" >
			<format type="amount" />
			<reject prompt="Amount_Justify">([transferAmount]=="" &amp;&amp; [debitAmount]=="") || ([transferAmount]== 0 &amp;&amp; [debitAmount]== 0)</reject>
			<reject prompt="Amount_Justify_1">[transferAmount]&lt;0 &amp;&amp; [debitAmount]&lt;0 </reject>
		</field>
		<field name="debitAmount" label="Transfer_Amount_Info2" >
			<format type="amount" />
		</field>		
	</group>
	<group name="corpRepatriate">
		<field name="fromCorporation" label="From_Corporation" required="yes">
			<format type="string" />
		</field>
		<field name="fromAccount" label="From_Account" required="yes">
			<format type="numonly" />
		</field>
		<field name="toAccount" label="To_Account" required="yes">
			<format type="numonly" />
			<reject prompt="From Account can not be the same as to Account">[fromAccount]==[toAccount]</reject>
		</field>
		<field name="transferAmount" label="To_Amount" >
			<format type="amount" />
			<reject prompt="Amount_Justify">([transferAmount]=="" &amp;&amp; [debitAmount]=="") || ([transferAmount]== 0 &amp;&amp; [debitAmount]== 0)</reject>
			<reject prompt="Amount_Justify_1">[transferAmount]&lt;0 &amp;&amp; [debitAmount]&lt;0 </reject>
		</field>
		<field name="debitAmount" label="Transfer_Amount_Info2" >
			<format type="amount" />
		</field>		
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/batch_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="bank_draft_check">
		<field name="uploadFile" label="choose_file" required="yes">
	</field>
	</group>
	<group name="cash_order_check">
		<field name="uploadFile" label="choose_file" required="yes">
	</field>
	</group>
	<group name="protection_cheque_check">
		<field name="uploadFile" label="choose_file" required="yes">
	</field>
	</group>
	<group name="stop_cheque_check">
		<field name="uploadFile" label="choose_file" required="yes">
	</field>
	</group>
	
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/time_deposit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="new_tdAccount">
		<field name="currentAccount" label="debit_account" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("currentAccount").selectedIndex == 0</reject>
		</field>
		<field name="currentAccountCcy" label="From_ccy" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("currentAccountCcy").selectedIndex == 0</reject>
		</field>
		<field name="currency" label="currency">
			<format type="string" />
			<reject prompt="currency_seleted">[currency]=="0"</reject>
			<reject prompt="Maturity_Instruction_Currency_Jusitify">[currency]!=[currentAccountCcy]</reject>
		</field>
		<field name="term" label="period">
			<format type="string" />
			<reject prompt="period_seletec">[term]=="0"</reject>
		</field>
		<field name="principal" label="amount" required="yes">
			<format type="amount"/>
			<reject prompt="amount_justify">[principal] &lt; 5000</reject>
		</field>
		<field name="currentAccount" label="current_account">
			<format type="string" />
			<reject prompt="account_seleted">[currentAccount]=="0"</reject>
		</field>
		<!-- add by linrui for add Maturity instruction -->
		<field name="instCd" label="Maturity_Instruction" required="no">
            <format type="string" />
			<reject prompt="Maturity_Instruction_Jusitify">document.getElementById("instCd").selectedIndex == 0</reject>
        </field>
		<!-- end -->
	</group>
	<group name="withdrawal_list">
		<field name="accountNo" label="account_no" required="yes">
		</field>
	</group>
	<group name="withdrawal">
		<field name="currentAccount" label="credit_ccount" required="no">
			<format type="string" />
			<reject prompt="Required">document.getElementById("currentAccount").selectedIndex == 0</reject>
		</field>
		<field name="fromCurrency" label="From_ccy" required="no">
			<format type="string" />
			<reject prompt="Required">document.getElementById("currentAccountCcy").selectedIndex == 0</reject>
		    <reject prompt="Maturity_Instruction_Currency_Jusitify">[currency]!=[currentAccountCcy]</reject>
		</field>
		<field name="currentAccountCcy" label="Credit_Currency" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("currentAccountCcy").selectedIndex == 0</reject>
		</field>
	</group>
	<group name="td_history">
		<field name="dateFrom" label="date_from" required="no">
			<format type="date"/>
			<reject prompt="Date_Justify">[date_range]=="range" &amp;&amp; ((getDateValue([dateFrom])>getDateValue([dateTo]) &amp;&amp; [dateTo] != "")|| (([dateFrom]=="") &amp;&amp; ([dateTo]=="")))</reject>
		</field>
		<field name="dateTo" label="date_to" required="no">
			<format type="date"/>
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/autopay.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="add">
		<field name="apsCode" label="PAYMENT_TYPE" required="true" />
		<field name="card_merchant" label="card_merchant" required="false"/>
		<field name="contractNo" label="CONTRACT_NUMBER_OR_CREDIT_CARD_NO" required="true">
			<format maxlen="16" />
			<!--<reject prompt="Contract_No_Format">[apsCode]!=[card_merchant]</reject>-->
			<reject prompt="Credit_Card_Format">
			[apsCode]==[card_merchant] &amp;&amp; 
			(
			([contractNo].charAt(0) == '3' &amp;&amp; [contractNo].length != 15)
			||
			([contractNo].charAt(0) != '3' &amp;&amp; [contractNo].length != 16)
			)
			</reject>
		</field>
		<field name="payOption" label="Pay_Option" required="true" />
		<field name="paymentLimit" label="Input_Amout" required="true" >
			<format type="autopay" maxlen="10"/>
			<reject prompt="AUTOPAY_NOT_ZERO">[paymentLimit]==0</reject>
			<reject prompt="AUTOPAY_NOT_DECIMAL">/^\+?(\d*\.\d*)$/.test([paymentLimit])  &amp;&amp; ! isNaN([paymentLimit])</reject>
			<!--<reject prompt="Input_Amout">[payOption]=="P"</reject>
		--></field>
		<field name="payAcct" label="PAYMENT_ACCOUNT" required="true"/>
	</group>
	<group name="list">
		<field name="status" label="">
			<reject prompt="Autopay_Status_Format">
				[status]!="0"
			</reject>
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/bill_payment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="template">
		<field name="transId" label="trans_id" required="yes">
		</field>
	</group>
	<group name="template_pay">
		<field name="fromAccount" label="debit_account">
			<format type="string" />
			<reject prompt="account_seleted">[fromAccount]=="0"</reject>
		</field>
	</group>
	<group name="template_add">
		<field name="category" label="category">
			<format type="string" />
			<reject prompt="category_selected">[category]=="0"</reject>
		</field>
		<field name="merchant" label="merchant">
			<format type="string" />
			<reject prompt="merchant_selected">[merchant]=="0"</reject>
		</field>
		<field name="fromAccount" label="debit_account">
			<format type="string" />
			<reject prompt="account_seleted">[fromAccount]=="0"</reject>
		</field>
		<field name="billNo1" label="billNo" required="yes">
			<format type="numonly"/>
		</field>
		<field name="transferAmount" label="payment_amount">
			<format type="amount"/>
			<reject prompt="amount_seleted">[payType]=="8" &amp;&amp; [transferAmount]==""</reject>
		</field>
	</group>
	<group name="template_edit">
		<field name="category" label="category">
			<format type="string" />
			<reject prompt="category_selected">[category]=="0"</reject>
		</field>
		<field name="merchant" label="merchant">
			<format type="string" />
			<reject prompt="merchant_selected">[merchant]=="0"</reject>
		</field>
		<field name="billNo1" label="billNo" required="yes">
			<format type="numonly"/>
		</field>
		<field name="fromAccount" label="debit_account">
			<format type="string" />
			<reject prompt="account_seleted">[fromAccount]=="0"</reject>
		</field>
	</group>
	<group name="general_payment_check">
		<field name="category" label="category">
			<format type="string" />
			<reject prompt="category_selected">[category]=="0"</reject>
		</field>
		<field name="merchant" label="merchant">
			<format type="string" />
			<reject prompt="merchant_selected">[merchant]=="0"</reject>
		</field>
		<field name="billNo1" label="billNo">
			<format type="string" />
			<reject prompt="bill_no_selected">[billNo1]=="0"</reject>
		</field>
		<field name="otherBillNo" label="other_bill_no">
			<format type="numonly" />
			<reject prompt="other_not_null">[billNo1]=="9" &amp;&amp; [otherBillNo]==""</reject>
		</field>
	</group>
	<group name="general_payment">
		<field name="fromAccount" label="debit_account">
			<format type="string" />
			<reject prompt="account_seleted">[fromAccount]=="0"</reject>
		</field>
	</group>
	<group name="card_payment_check">
		<field name="billNo1" label="card_no" required="yes">
			<format type="numonly"/>
		</field>
	</group>
	<group name="card_payment">
		<field name="fromAccount" label="debit_account">
			<format type="string" />
			<reject prompt="account_seleted">[fromAccount]=="0"</reject>
		</field>
		<field name="transferAmount" label="payment_amount" required="yes">
			<format type="amount"/>
		</field>
	</group>
	<group name="tax_payment_check">
		<field name="billType" label="tax_category">
			<format type="string" />
			<reject prompt="tax_category_selected">[billType]=="0"</reject>
		</field>
		<field name="billNo1" label="nr_conhecimento" required="yes">
			<format type="numonly"/>
		</field>
		<field name="billNo2" label="nr_contribuinte" required="yes">
			<format type="numonly"/>
		</field>
	</group>
	<group name="tax_payment">
		<field name="fromAccount" label="debit_account">
			<format type="string" />
			<reject prompt="account_seleted">[fromAccount]=="0"</reject>
		</field>
	</group>
	<group name="payment_history">
		<field name="dateFrom" label="date_from" required="no">
			<format type="date"/>
			<reject prompt="Date_Justify">[date_range]=="range" &amp;&amp; ((getDateValue([dateFrom])>getDateValue([dateTo]) &amp;&amp; [dateTo] != "") || (([dateFrom]=="") &amp;&amp; ([dateTo]=="")))</reject>
        </field>
		<field name="dateTo" label="date_to" required="no">
			<format type="date"/>
		</field>
	</group>
</fieldchecking>
