=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/fieldchecking.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by nabai (enlogic) -->
<!ENTITY % Boolean "(true|false|yes|no)">
<!ENTITY % Integer "CDATA">
<!ENTITY % PropName "CDATA">
<!ENTITY % FieldFormat "(string|numonly|engonly|engnum|date|time|amount|integer|phoneno|email)">
<!ELEMENT fieldchecking (group*)>
<!ELEMENT group (field*)>
<!ATTLIST group
	name %PropName; #REQUIRED
>
<!ELEMENT field (format?, depend*, reject*)>
<!ATTLIST field
	name %PropName; #REQUIRED
	label %PropName; #REQUIRED
	required %Boolean; #IMPLIED
>
<!ELEMENT format (#PCDATA)>
<!ATTLIST format
	type %PropName; #REQUIRED
	fixlen %Integer; #IMPLIED
	maxlen %Integer; #IMPLIED
	minlen %Integer; #IMPLIED
	prefix %Integer; #IMPLIED
	suffix %Integer; #IMPLIED
>
<!ELEMENT depend (#PCDATA)>
<!ATTLIST depend
	prompt %PropName; #REQUIRED
>
<!ELEMENT reject (#PCDATA)>
<!ATTLIST reject
	prompt %PropName; #REQUIRED
>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/sch_transfer_history.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="schTransferHistory">
		<field name="beneficiaryType" label="Schedule_Business_type" required="yes">
			<format type="string" />
		</field>
		<field name="dateFrom" label="date_from" required="no">
			<format type="date"/>
			<reject prompt="Date_Justify">[date_range]=="range" &amp;&amp; ((getDateValue([dateFrom])>getDateValue([dateTo]) &amp;&amp; [dateTo] != "") || (([dateFrom]=="") &amp;&amp; ([dateTo]=="")))</reject>
        </field>
		<field name="dateTo" label="date_to" required="no">
			<format type="date"/>
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/corp_account.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="acc_load">
		<field name="corpID" label="corp_Id" required="yes">
			<format type="numonly" maxlen="12"/>
		</field>
	</group>
	<group name="acc_add">
		<field name="offlineAcc" label="not_online_account" required="yes">
		</field>
	</group>
	<group name="acc_remove">
		<field name="onlineAcc" label="online_account" required="yes">
		</field>
	</group>
	<group name="all_limits_set">
		<field name="allLimits" label="all_account_limits" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([allLimits]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
	</group>
	<group name="limit_set">
		<!-- Modify by long_zg 2019-05-22 UAT6-245 COB：四種轉賬的名稱需要更改 begin -->
		<!--<field name="limit1" label="online_own_accounts" required="yes">-->
		<field name="limit1" label="TO_MY_ACCOUNT" required="yes">
		<!-- Modify by long_zg 2019-05-22 UAT6-245 COB：四種轉賬的名稱需要更改 end -->
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit1]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit2" label="accounts_in_bank" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit2]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit3" label="accounts_in_macau" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit3]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit4" label="accounts_in_overseas" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit4]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit5" label="corp_fund_allocation" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit5]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit6" label="bill_payment" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit6]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit7" label="time_deposit" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit7]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit8" label="payroll" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit8]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit9" label="bank_draft" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit9]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
		<field name="limit10" label="cashier_order" required="yes">
			<format type="amount" maxlen="15"/>
			<reject prompt="EXCEED_MAXIMUM_LIMIT">!([limit10]&lt;(Number([dailyLimit])+0.01))</reject>
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/bank_user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="bankuser">
		<field name="userId" label="User_Id" required="yes">
			<format type="string" />
		</field>
		<field name="userName" label="User_Name" required="yes">
			<format type="string"/>
		</field>
		<field name="email" label="Email" required="yes">
			<format type="email"/>
		</field>
		
		<field name="userPassword" label="PIN" required="yes">
			<format type="string" minlen="6" maxlen="12"/>
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/transferTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="transferTemplate">
		<field name="fromAccount" label="FromAccount" required="yes">
			<format type="String" />
		</field>
		<field name="toAccount" label="ToAccount" required="yes">
			<format type="String" />
		</field>
		<field name="transferAmount" label="Amount" required="yes">
			<format type="String" />
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="login">
	    <field name="cifNo" label="CIF_NO" required="yes">
			<format type="string" />
		</field>
		<field name="loginId" label="Login_Id" required="yes">
			<format type="string" />
		</field>
		<field name="password" label="PIN" required="yes">
			<format type="string" />
			<reject prompt="Password_Range">([password].length &lt; 8) || ([password].length &gt; 20)</reject>
		</field>
		
		
		<!-- Add by long_zg 2019-05-16 for otp login -->
		<field name="otp" label="OTP">
			<format type="string" />
			<reject prompt="OTP_REQUIRED">[otpLogin]=="Y" &amp; [otp] ==""</reject>
		</field>
		<!-- Add by long_zg 2019-05-16 for otp end -->
	</group>
	<group name="changePin">
		<field name="oldPassword" label="Initail_PIN" required="yes">
			<format type="String" />
		</field>
        <field name="newPassword" label="New_PIN" required="yes">
			<format type="String" />
			<reject prompt="Password_Info1">[newPassword]==[oldPassword]</reject>
			<reject prompt="Password_Range">([newPassword].length &lt; 8) || ([newPassword].length &gt; 20)</reject>
			<reject prompt="Password_Upper_Lower">(parseInt([checkUpperNum]) &lt; pin_upper) || (parseInt([checkLowerNum]) &lt; pin_lower)</reject>
			
			<!-- add by long_zg 2015-06-24 for CR210 New policy to BOB/BOL password -->
			<reject prompt="Char_Num_Only">checkCharNum([newPassword])</reject>
			<reject prompt="Password_UserId_Same">([newPassword].toLowerCase()  == [userId].toLowerCase())</reject>
			<reject prompt="Password_UserId_Reverse_Same">([newPassword].toLowerCase()  == ([userId].split('').reverse().join('')).toLowerCase())</reject>
			<reject prompt="Password_Include_IdNo">((''!=[idNo]) &amp;&amp; (-1 != [newPassword].toLowerCase() .indexOf((eliminate([idNo])).toLowerCase())))</reject>
			
		</field>
		<field name="confirmPassword" label="New_PIN_Confirm" required="yes">
			<format type="String" />
			<depend prompt="Password_Info">[newPassword]==[confirmPassword]</depend>
		</field>
	</group>
	<group name="changePin2">
        <field name="newSecurityCode" label="New_S_Code" required="yes">
			<format type="String" />
			<reject prompt="SecurityCode_Range">([newSecurityCode].length &lt; pin2_min) || ([newSecurityCode].length &gt; pin2_max)</reject>
			<reject prompt="SecurityCode_Upper_Lower">(parseInt([checkUpperNum]) &lt; pin2_upper) || (parseInt([checkLowerNum]) &lt; pin2_lower)</reject>
			
			<!-- add by long_zg 2015-06-24 for CR210 New policy to BOB/BOL password -->
			<reject prompt="Char_Num_Only">checkCharNum([newSecurityCode])</reject>
			<reject prompt="Password_UserId_Same">([newSecurityCode].toLowerCase()  == [userId].toLowerCase())</reject>
			<reject prompt="Password_UserId_Reverse_Same">([newSecurityCode].toLowerCase()  == ([userId].split('').reverse().join('')).toLowerCase())</reject>
			<reject prompt="Password_Include_IdNo">((''!=[idNo]) &amp;&amp; (-1 != [newSecurityCode].toLowerCase() .indexOf((eliminate([idNo])).toLowerCase())))</reject>
		</field>
		<field name="confirmSecurityCode" label="New_S_Code_Confirm" required="yes">
			<format type="String" />
			<depend prompt="SecurityCode_Info">[newSecurityCode]==[confirmSecurityCode]</depend>
		</field>
		<field name="OldSecurityCode" label="Old Security Code" required="yes">
			<format type="String" />
		</field>
	</group>
	<group name="inputSecurityCode">
        <field name="securityCode" label="security_code" required="yes">
			<format type="String" />
		</field>
		<field name="OldSecurityCode" label="Old Security Code" required="yes">
			<format type="String" />
		</field>
		
	</group>

	<group name="bank_changePin">
		<field name="oldPassword" label="Initail_PIN" required="yes">
			<format type="String" minlen="6" />
		</field>
        <field name="newPassword" label="New_PIN" required="yes">
			<format type="String" minlen="6" />
			<reject prompt="Password_Info1">[newPassword]==[oldPassword]</reject>
		</field>
		<field name="confirmPassword" label="New_PIN_Confirm" required="yes">
			<format type="String" />
			<depend prompt="Password_Info">[newPassword]==[confirmPassword]</depend>
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/estatement_history.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
   <group name="estatementHistory">
		<field name="dateFrom" label="Begin_time" required="no">
		     <format type="date" />
		     <reject prompt="Date_Justify_Begin">document.getElementById("dateRange").selectedIndex == 0 &amp;&amp; [dateFrom]==""</reject>
			<reject prompt="Date_Justify">document.getElementById("dateRange").selectedIndex == 0 &amp;&amp;[date_range]=="range" &amp;&amp; ((getDateValue([dateFrom])>getDateValue([dateTo]) &amp;&amp; [dateTo] != "")|| (([dateFrom]=="") &amp;&amp; ([dateTo]=="")))</reject> 
		</field>
		<field name="dateTo" label="End_time" required="no">
		     <format type="date" />
		     <reject prompt="Date_Justify_End">document.getElementById("dateRange").selectedIndex == 0 &amp;&amp; [dateTo]==""</reject>
		</field>
	</group>
	
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/auth_pref.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="setRules">
		<field name="ruleType" label="Auth_Type" required="yes">
			<format type="string"/>
		</field>
		<field name="singleLevel" label="Single_Class">
			<format type="string"/>
			<reject prompt="Single_Level_Must_Set">[ruleType]=="0" &amp;&amp; [singleLevel]==""</reject>
		</field>
	</group>
	<group name="multiRules">
		<field name="fromAmount0" label="From_Amount0"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount0" label="To_Amount0">
			<format type="amount"/>
		</field>
		<field name="levelA0" label="Level_A0">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA0]=="0" || [levelA0]=="") &amp;&amp; ([levelB0]=="0" || [levelB0]=="") &amp;&amp; ([levelC0]=="0" || [levelC0]=="") &amp;&amp; ([levelD0]=="0" || [levelD0]=="") &amp;&amp; ([levelE0]=="0" || [levelE0]=="")</reject>
		</field>
		<field name="levelB0" label="Level_B0">
			<format type="numonly"/>
		</field>
		<field name="levelC0" label="Level_C0">
			<format type="numonly"/>
		</field>
		<field name="levelD0" label="Level_D0">
			<format type="numonly"/>
		</field>
		<field name="levelE0" label="Level_E0">
			<format type="numonly"/>
		</field>
		<field name="fromAmount1" label="From_Amount1"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount1" label="To_Amount1">
			<format type="amount"/>
		</field>
		<field name="levelA1" label="Level_A1">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA1]=="0" || [levelA1]=="") &amp;&amp; ([levelB1]=="0" || [levelB1]=="") &amp;&amp; ([levelC1]=="0" || [levelC1]=="") &amp;&amp; ([levelD1]=="0" || [levelD1]=="") &amp;&amp; ([levelE1]=="0" || [levelE1]=="")</reject>
		</field>
		<field name="levelB1" label="Level_B1">
			<format type="numonly"/>
		</field>
		<field name="levelC1" label="Level_C1">
			<format type="numonly"/>
		</field>
		<field name="levelD1" label="Level_D1">
			<format type="numonly"/>
		</field>
		<field name="levelE1" label="Level_E1">
			<format type="numonly"/>
		</field>
		<field name="fromAmount2" label="From_Amount2"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount2" label="To_Amount2">
			<format type="amount"/>
		</field>
		<field name="levelA2" label="Level_A2">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA2]=="0" || [levelA2]=="") &amp;&amp; ([levelB2]=="0" || [levelB2]=="") &amp;&amp; ([levelC2]=="0" || [levelC2]=="") &amp;&amp; ([levelD2]=="0" || [levelD2]=="") &amp;&amp; ([levelE2]=="0" || [levelE2]=="")</reject>
		</field>
		<field name="levelB2" label="Level_B2">
			<format type="numonly"/>
		</field>
		<field name="levelC2" label="Level_C2">
			<format type="numonly"/>
		</field>
		<field name="levelD2" label="Level_D2">
			<format type="numonly"/>
		</field>
		<field name="levelE2" label="Level_E2">
			<format type="numonly"/>
		</field>
		<field name="fromAmount3" label="From_Amount3"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount3" label="To_Amount3">
			<format type="amount"/>
		</field>
		<field name="levelA3" label="Level_A3">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA3]=="0" || [levelA3]=="") &amp;&amp; ([levelB3]=="0" || [levelB3]=="") &amp;&amp; ([levelC3]=="0" || [levelC3]=="") &amp;&amp; ([levelD3]=="0" || [levelD3]=="") &amp;&amp; ([levelE3]=="0" || [levelE3]=="")</reject>
		</field>
		<field name="levelB3" label="Level_B3">
			<format type="numonly"/>
		</field>
		<field name="levelC3" label="Level_C3">
			<format type="numonly"/>
		</field>
		<field name="levelD3" label="Level_D3">
			<format type="numonly"/>
		</field>
		<field name="levelE3" label="Level_E3">
			<format type="numonly"/>
		</field>
		<field name="fromAmount4" label="From_Amount4"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount4" label="To_Amount4">
			<format type="amount"/>
		</field>
		<field name="levelA4" label="Level_A4">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA4]=="0" || [levelA4]=="") &amp;&amp; ([levelB4]=="0" || [levelB4]=="") &amp;&amp; ([levelC4]=="0" || [levelC4]=="") &amp;&amp; ([levelD4]=="0" || [levelD4]=="") &amp;&amp; ([levelE4]=="0" || [levelE4]=="")</reject>
		</field>
		<field name="levelB4" label="Level_B4">
			<format type="numonly"/>
		</field>
		<field name="levelC4" label="Level_C4">
			<format type="numonly"/>
		</field>
		<field name="levelD4" label="Level_D4">
			<format type="numonly"/>
		</field>
		<field name="levelE4" label="Level_E4">
			<format type="numonly"/>
		</field>
		<field name="fromAmount5" label="From_Amount5"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount5" label="To_Amount5">
			<format type="amount"/>
		</field>
		<field name="levelA5" label="Level_A5">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA5]=="0" || [levelA5]=="") &amp;&amp; ([levelB5]=="0" || [levelB5]=="") &amp;&amp; ([levelC5]=="0" || [levelC5]=="") &amp;&amp; ([levelD5]=="0" || [levelD5]=="") &amp;&amp; ([levelE5]=="0" || [levelE5]=="")</reject>
		</field>
		<field name="levelB5" label="Level_B5">
			<format type="numonly"/>
		</field>
		<field name="levelC5" label="Level_C5">
			<format type="numonly"/>
		</field>
		<field name="levelD5" label="Level_D5">
			<format type="numonly"/>
		</field>
		<field name="levelE5" label="Level_E5">
			<format type="numonly"/>
		</field>
		<field name="fromAmount6" label="From_Amount6"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount6" label="To_Amount6">
			<format type="amount"/>
		</field>
		<field name="levelA6" label="Level_A6">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA6]=="0" || [levelA6]=="") &amp;&amp; ([levelB6]=="0" || [levelB6]=="") &amp;&amp; ([levelC6]=="0" || [levelC6]=="") &amp;&amp; ([levelD6]=="0" || [levelD6]=="") &amp;&amp; ([levelE6]=="0" || [levelE6]=="")</reject>
		</field>
		<field name="levelB6" label="Level_B6">
			<format type="numonly"/>
		</field>
		<field name="levelC6" label="Level_C6">
			<format type="numonly"/>
		</field>
		<field name="levelD6" label="Level_D6">
			<format type="numonly"/>
		</field>
		<field name="levelE6" label="Level_E6">
			<format type="numonly"/>
		</field>
		<field name="fromAmount7" label="From_Amount7"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount7" label="To_Amount7">
			<format type="amount"/>
		</field>
		<field name="levelA7" label="Level_A7">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA7]=="0" || [levelA7]=="") &amp;&amp; ([levelB7]=="0" || [levelB7]=="") &amp;&amp; ([levelC7]=="0" || [levelC7]=="") &amp;&amp; ([levelD7]=="0" || [levelD7]=="") &amp;&amp; ([levelE7]=="0" || [levelE7]=="")</reject>
		</field>
		<field name="levelB7" label="Level_B7">
			<format type="numonly"/>
		</field>
		<field name="levelC7" label="Level_C7">
			<format type="numonly"/>
		</field>
		<field name="levelD7" label="Level_D7">
			<format type="numonly"/>
		</field>
		<field name="levelE7" label="Level_E7">
			<format type="numonly"/>
		</field>
		<field name="fromAmount8" label="From_Amount8"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount8" label="To_Amount8">
			<format type="amount"/>
		</field>
		<field name="levelA8" label="Level_A8">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA8]=="0" || [levelA8]=="") &amp;&amp; ([levelB8]=="0" || [levelB8]=="") &amp;&amp; ([levelC8]=="0" || [levelC8]=="") &amp;&amp; ([levelD8]=="0" || [levelD8]=="") &amp;&amp; ([levelE8]=="0" || [levelE8]=="")</reject>
		</field>
		<field name="levelB8" label="Level_B8">
			<format type="numonly"/>
		</field>
		<field name="levelC8" label="Level_C8">
			<format type="numonly"/>
		</field>
		<field name="levelD8" label="Level_D8">
			<format type="numonly"/>
		</field>
		<field name="levelE8" label="Level_E8">
			<format type="numonly"/>
		</field>
		<field name="fromAmount9" label="From_Amount9"  required="yes">
			<format type="amount"/>
		</field>
		<field name="toAmount9" label="To_Amount9">
			<format type="amount"/>
		</field>
		<field name="levelA9" label="Level_A9">
			<format type="numonly"/>
			<reject prompt="Level_Must_Set">([levelA9]=="0" || [levelA9]=="") &amp;&amp; ([levelB9]=="0" || [levelB9]=="") &amp;&amp; ([levelC9]=="0" || [levelC9]=="") &amp;&amp; ([levelD9]=="0" || [levelD9]=="") &amp;&amp; ([levelE9]=="0" || [levelE9]=="")</reject>
		</field>
		<field name="levelB9" label="Level_B9">
			<format type="numonly"/>
		</field>
		<field name="levelC9" label="Level_C9">
			<format type="numonly"/>
		</field>
		<field name="levelD9" label="Level_D9">
			<format type="numonly"/>
		</field>
		<field name="levelE9" label="Level_E9">
			<format type="numonly"/>
		</field>
	</group>
</fieldchecking>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/fieldchkxml/schedule_transfer_BANK.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fieldchecking SYSTEM "fieldchecking.dtd">
<fieldchecking>
	<group name="schedule_bank">
	    <field name="scheduleName" label="Schedule_Name" required="yes">
			<format type="String" />
		</field>
		<field name="dayType" label="Frequence" required="yes">
			<reject prompt="Weekly_Justify">
				[dayType]=="2" &amp;&amp; [frequenceWeekDays]==null
			</reject>
			<reject prompt="Monthly_Justify">
				[dayType]=="3" &amp;&amp; [month_type]==null
			</reject>
			<reject prompt="monthly_designed_day_format_error">
				[dayType]=="3" &amp;&amp; [month_type]==0 &amp;&amp;
				([designed_day]&lt;1 || [designed_day]&gt;31)
			</reject>
			<reject prompt="Days_per_month_Justify">
				[dayType]=="4" &amp;&amp; [days_per_month]==""
			</reject>
		</field>
		<field name="fromAccount" label="From Account" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("fromAccount").selectedIndex == 0</reject>
		</field>
		<field name="fromCurrency" label="From Currency" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("fromCurrency").selectedIndex == 0</reject>
		</field>
		<field name="toAccount" label="To Account" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("toAccount").selectedIndex == 0</reject>
		</field>
		<field name="toCurrency" label="To Currency" required="no">
			<format type="numonly" />
			<reject prompt="Required">document.getElementById("toCurrency").selectedIndex == 0</reject>
		</field>
		<field name="transferAmount" label="To_Amount">
			<format type="amount" />
			<reject prompt="Amount_Justify">([transferAmount]=="" &amp;&amp; [debitAmount]=="") || ([transferAmount]== 0 &amp;&amp; [debitAmount]== 0)</reject>
			<reject prompt="Amount_Justify_1">[transferAmount]&lt;10 &amp;&amp; [debitAmount]&lt;10 </reject>			
		</field>
		<field name="debitAmount" label="Transfer_Info1" >
			<format type="amount" />
		</field>
		<!-- add by linrui 20190531 -->
		<field name="endDate" label="Transfer_End_Date" required="yes">
			<format type="date"/>
		</field>
	</group>
</fieldchecking>
