=== liuzhigang1996/demo/cib/WebContent/WEB-INF/neturbo-menu.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT menu-setting (menu*)>
<!ATTLIST menu-setting
	resource CDATA #IMPLIED
>

<!ELEMENT menu (menu*)>
<!ATTLIST menu
	mid CDATA #REQUIRED
	name CDATA #IMPLIED
	type CDATA #IMPLIED
	label CDATA #IMPLIED
	class CDATA #IMPLIED
	permission CDATA #IMPLIED
	path CDATA #IMPLIED
	target CDATA #IMPLIED
>

=== liuzhigang1996/demo/cib/WebContent/WEB-INF/menu-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE menu-setting SYSTEM "neturbo-menu.dtd">
<menu-setting resource="app.cib.resource.sys.menu">
	<menu type="group" mid="main" target="mainFrame">
	 
		<menu type="group" mid="Authorization" label="Authorization" class="app.cib.util.MenuCorp">
			<menu type="item" mid="PendingApproval" permission="aut.corp" label="Pending Approval List" path="/cib/approve.do?ActionMethod=list"/>
			<menu type="item" mid="AuthStatus" permission="aut.corp" label="Outstanding Authorizations" path="/cib/approve.do?ActionMethod=statusEnquiry&amp;procStatus=P"/>
			<menu type="item" mid="AuthHistory" permission="aut.corp" label="Authorization History Enquiry" path="/cib/approve.do?ActionMethod=historyEnquiryLoad"/>
		</menu>
		<menu type="group" mid="TransationExecution" label="Transaction Execution">
			<menu type="item" mid="PendingExecuction" permission="aut.exec" label="Pending Execution List" path="/cib/approve.do?ActionMethod=list"/>
		</menu>
		<menu type="group" mid="AuthorizationBank" label="Authorization">
			<menu type="item" mid="PendingApprovalBank" permission="bnk.aut" label="Pending Approval List" path="/cib/approve.do?ActionMethod=list"/>
			<menu type="item" mid="AuthStatusBank" permission="bnk.aut" label="Outstanding Authorizations" path="/cib/approve.do?ActionMethod=statusEnquiry&amp;procStatus=P"/>
			<menu type="item" mid="AuthHistoryBank" permission="bnk.aut" label="Authorization History Enquiry" path="/cib/approve.do?ActionMethod=historyEnquiryLoad"/>
		</menu>
		<menu type="group" mid="CorpPreferencesForSupervisor" label="Company Preferences">
			<menu type="item" mid="CorporationList" permission="srv.bank.supervisor" label="Company List" path="/cib/corporationForSupervisor.do?ActionMethod=list"/>
		 	<menu type="item" mid="ViewAccounts" permission="srv.bank.supervisor" label="Accounts" path="/cib/corporationForSupervisor.do?ActionMethod=prefEntry&amp;prefType=account"/>
			<menu type="item" mid="ViewLimits" permission="srv.bank.supervisor" label="Transaction Limits" path="/cib/corporationForSupervisor.do?ActionMethod=prefEntry&amp;prefType=limit"/>
			<menu type="item" mid="ViewUsers" permission="srv.bank.supervisor" label="Company Users" path="/cib/corporationForSupervisor.do?ActionMethod=prefEntry&amp;prefType=user"/>
			<menu type="item" mid="ViewAuthPreferences" permission="srv.bank.supervisor" label="Authorization Preferences" path="/cib/corporationForSupervisor.do?ActionMethod=prefEntry&amp;prefType=auth"/>
			<menu type="item" mid="SetSubsidiarys" permission="srv.bank.supervisor" label="Subsidiaries" path="/cib/corporationForSupervisor.do?ActionMethod=prefEntry&amp;prefType=subsidiary"/>
			<menu type="item" mid="viewGroups" permission="srv.bank.supervisor" label="User Groups" path="/cib/corporationForSupervisor.do?ActionMethod=prefEntry&amp;prefType=group"/>
			<menu type="item" mid="configChecking" permission="srv.bank.supervisor" label="Configuration Checking" path="/cib/corporationForSupervisor.do?ActionMethod=prefEntry&amp;prefType=checking"/>
			<!--<menu type="item" mid="AccountAuth" permission="srv.bank.supervisor" label="Account Authorization" path="/cib/corporationForSupervisor.do?ActionMethod=prefEntry&amp;prefType=acctauth"/>-->
		</menu>
		
        <!-- Jet 2007.09.27 end -->
		<menu type="group" mid="AccountEnquiry" label="Own Accounts">
			<menu type="item" mid="AccountSummary" permission="enq" class="app.cib.util.MenuCorp" label="Accounts Summary" path="/cib/accEnquiry.do?ActionMethod=listAccountSummary"/>
			<menu type="item" mid="CurrentAccount" permission="enq" class="app.cib.util.MenuCorp" label="Current Accounts" path="/cib/accEnquiry.do?ActionMethod=listCurrentAccount"/>
			<menu type="item" mid="SavingAccount" permission="enq" class="app.cib.util.MenuCorp" label="Savings Accounts" path="/cib/accEnquiry.do?ActionMethod=listSavingAccount"/>
			<menu type="item" mid="TimeDeposits" permission="enq" class="app.cib.util.MenuCorp" label="Time Deposits" path="/cib/accEnquiry.do?ActionMethod=listTimeDeposit"/>
			<!--<menu type="item" mid="OverdraftAccount" permission="enq" class="app.cib.util.MenuCorp" label="Overdraft Accounts" path="/cib/accEnquiry.do?ActionMethod=listOverdraftAccount"/>-->
			<menu type="item" mid="LoanAccount" permission="enq" class="app.cib.util.MenuCorp" label="Loan Accounts" path="/cib/accEnquiry.do?ActionMethod=listLoanAccount"/>
			<!--<menu type="item" mid="CreditAccount" permission="enq" class="app.cib.util.MenuCorp" label="Credit_Account" path="/cib/accEnquiry.do?ActionMethod=listCreditAccount"/>-->
			<!--
			
			<menu type="item" mid="AuthStatusOper" permission="txn" label="Outstanding Authorizations" path="/cib/approve.do?ActionMethod=statusEnquiry&amp;procStatus=P"/>
			--><menu type="item" mid="NameAccount" permission="enq.nameAcc" class="app.cib.util.MenuCorp" label="Name Account" path="/cib/corpAccount.do?ActionMethod=nameAccountLoad"/>
			
		</menu>
		
		<!--  Delete by long_zg 2019-05-22 UAT6-457 COB：company setting菜單項問題 begin  -->
		<!--<menu type="group" mid="CorpInfo" label="Company Settings">
			<menu type="item" mid="ViewAccounts" permission="sys.corpinfo" label="Account List" path="/cib/corpInfo.do?ActionMethod=viewAccInfoList"/>
			<menu type="item" mid="ViewLimits" permission="sys.corpinfo" label="Transaction Limits" path="/cib/corpInfo.do?ActionMethod=viewAccLimitsList"/>
			<menu type="item" mid="ViewAuthPreferences" permission="sys.corpinfo" label="Authorization Preferences" path="/cib/corpInfo.do?ActionMethod=viewAuthPrefList"/>
			<menu type="item" mid="ViewCorpUser" permission="sys.corpinfo" label="Users" path="/cib/corpInfo.do?ActionMethod=viewCorpUserList"/>
			<menu type="item" mid="NameAccount" permission="adm.nameacct" class="app.cib.util.MenuCorp" label="Name Account" path="/cib/corpAccount.do?ActionMethod=nameAccountLoad"/>
		</menu>
		--><!--  Delete by long_zg 2019-05-22 UAT6-457 COB：company setting菜單項問題 end  -->
        <menu type="group" mid="Transfer" label="Transfers">
        	<!--  Modify by long_zg 2019-05-22 UAT6-245 COB：四種轉賬的名稱需要更改 begin  -->
			<!--
			<menu type="item" mid="AccountsBANK" permission="txn.transfer" label="To Accounts in BANK" path="/cib/transferInBANK.do?ActionMethod=addLoad"/>
			<menu type="item" mid="AccountsBANK3rd" permission="txn.transfer" label="To Accounts in BANK 3rd" path="/cib/transferInBANK3rd.do?ActionMethod=addLoad"/>
			<menu type="item" mid="AccountsMacau" permission="txn.transfer" label="To Accounts in Other Banks in Macau" path="/cib/transferInMacau.do?ActionMethod=addLoad"/>
			<menu type="item" mid="AccountsOverseas" permission="txn.transfer" label="To Accounts in Banks Overseas" path="/cib/transferInOversea.do?ActionMethod=addLoad"/>
			-->
			<menu type="item" mid="AccountsBANK" permission="txn.transfer" label="To My Account" path="/cib/transferInBANK.do?ActionMethod=addLoad"/>
			<menu type="item" mid="AccountsBANKMDB" permission="txn.transfer" label="To MDB Bank Account" path="/cib/transferInBANK3rd.do?ActionMethod=addLoad3rd&amp;ownerAccFlag=N"/>
			<menu type="item" mid="AccountsMacau" permission="txn.transfer" label="To Local Bank Account" path="/cib/transferInMacau.do?ActionMethod=addLoad"/>
			<menu type="item" mid="AccountsOverseas" permission="txn.transfer" label="To Overseas Bank Account" path="/cib/transferInOversea.do?ActionMethod=addLoad"/>
			<!--  Modify by long_zg 2019-05-22 UAT6-245 COB：四種轉賬的名稱需要更改 end  -->
			<menu type="item" mid="TransferTemplate" permission="txn.transfer" label="Transfer Templates" path="/cib/transferTemplate.do?ActionMethod=listTemplate"/>
			<menu type="item" mid="TransferHistory" permission="txn.transfer" label="Transfer History" path="/cib/transferHistory.do?ActionMethod=listLoad"/>
		</menu>
		<!-- modified by lzg 20190611 -->
	    <!--<menu type="group" mid="BatchTransfer" label="Batch Transfers">
			<menu type="item" mid="AccountsBankStM" permission="txn.transfer" label="Single To Multi Accounts in BANK" path="/cib/transferInBankStM.do?ActionMethod=uploadFileLoad"/>
			<menu type="item" mid="AccountsBankMtS" permission="txn.transfer" label="Multi To Single Accounts in BANK" path="/cib/transferInBankMtS.do?ActionMethod=uploadFileLoad"/>
			
			<menu type="item" mid="AccountsMacauStM" permission="txn.transfer" label="Single To Multi Accounts in Macau" path="/cib/transferInMacauStM.do?ActionMethod=uploadFileLoad"/>
			<menu type="item" mid="AccountsOverseaStM" permission="txn.transfer" label="Single To Multi Accounts Overseas" path="/cib/transferInOverseaStM.do?ActionMethod=uploadFileLoad"/>
		    
		</menu>	
		--><!-- modified by lzg 20190611 -->	  
		<!-- mod by linrui for oracle 
        	<menu type="group" mid="CorpFundAllocation" label="Fund Allocation" class="app.cib.util.MenuCorp">
			<menu type="item" mid="Delivery" permission="txn.corp" label="Delivery To Subsidiary" path="/cib/corpDelivery.do?ActionMethod=addLoad"/>
			<menu type="item" mid="BetweenSubsidiary" permission="txn.corp"  label="Transfer Between Subsidiaries" path="/cib/corpSubsidiaryTransfer.do?ActionMethod=addLoad"/>
			<menu type="item" mid="Repatriate" permission="txn.corp"  label="Repatriate From Subsidiary" path="/cib/corpRepatriate.do?ActionMethod=addLoad"/>
			<menu type="item" mid="FundAllocationHistory" permission="txn.corp" label="Fund Allocation History" path="/cib/corpHistory.do?ActionMethod=listLoad"/>
		</menu>
        -->
        <!-- mod by linrui for oracle
		<menu type="group" mid="PayBills" label="Bill Payment">
			<menu type="item" mid="FrequentPaymentList" permission="txn.pay" label="Frequent Payment List" path="/cib/templatePayment.do?ActionMethod=listTemplate"/>
			<menu type="item" mid="GeneralPayment" permission="txn.pay" label="General Payment" path="/cib/billPayment.do?ActionMethod=generalPaymentLoad"/>
			<menu type="item" mid="CreditCard" permission="txn.pay" label="Credit Card Payment" path="/cib/billPayment.do?ActionMethod=cardPaymentLoad"/>
